# This file was generated by GoReleaser. DO NOT EDIT.
cask "prizmal" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "prizmal"], chdir: ".", must_succeed: false
    end
  end

  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "05d66097031c6548db3e28469a6a223b5209b0603cab4860b41fabc8b83d285c"
      url "https://github.com/PrizmalAi/prizmal-cli/releases/download/v#{version}/prizmal-cli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "089aae4eeb0fd586e10c19df7da2d57073d1518dd27f0792a283d16972515ec6"
      url "https://github.com/PrizmalAi/prizmal-cli/releases/download/v#{version}/prizmal-cli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d1bb2941082166048437e92be219d665fd2d9dc497258419063a4f2aa512b3b4"
      url "https://github.com/PrizmalAi/prizmal-cli/releases/download/v#{version}/prizmal-cli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2e82748c71a1fc6285f6030101a93cb6ae32ed7f818f87c94d1f5aee7c823e8c"
      url "https://github.com/PrizmalAi/prizmal-cli/releases/download/v#{version}/prizmal-cli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "prizmal"
  desc "Use Prizmal Switch with any coding-agent harness"
  homepage "https://github.com/PrizmalAi/prizmal-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "prizmal"

  # No zap stanza required
end
