# This file was generated by GoReleaser. DO NOT EDIT.
cask "prizmal" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "prizmal"], chdir: ".", must_succeed: false
    end
  end

  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "1b2d1de478899ffafb762a41af3b69aa2f5dbac9d2f499bd456d58cd11f0bb14"
      url "https://github.com/PrizmalAi/prizmal-cli/releases/download/v#{version}/prizmal-cli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "68b9bf5d1199f988ac01fa698a94e4bda9cfcdebdc7482ad3fd147787c50f341"
      url "https://github.com/PrizmalAi/prizmal-cli/releases/download/v#{version}/prizmal-cli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f1c5bfdd4903d4016728ad84be9039c363a59ed7d297cd6b71f30a8934bf7d5d"
      url "https://github.com/PrizmalAi/prizmal-cli/releases/download/v#{version}/prizmal-cli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "61ff0f675c3f36e65da4e9b975a251a2c066a9d5436134455745a70f0d28d31f"
      url "https://github.com/PrizmalAi/prizmal-cli/releases/download/v#{version}/prizmal-cli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "prizmal"
  desc "Use Prizmal Switch with any coding-agent harness"
  homepage "https://github.com/PrizmalAi/prizmal-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "prizmal"

  # No zap stanza required
end
