# This file was generated by GoReleaser. DO NOT EDIT.
cask "prizmal" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "prizmal"], chdir: ".", must_succeed: false
    end
  end

  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "91425a3939693dc9238abd9e9f9a46938564054b73b008163368699fc4492f28"
      url "https://github.com/PrizmalAi/prizmal-cli/releases/download/v#{version}/prizmal-cli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "430087692152767e44a538fbecb6b2deb844d7633861d094d32f871d52844255"
      url "https://github.com/PrizmalAi/prizmal-cli/releases/download/v#{version}/prizmal-cli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "10230a92fb41afbdbfa7799d79d1fe83c4ccbacf9dc360ff4028750b628ceb5b"
      url "https://github.com/PrizmalAi/prizmal-cli/releases/download/v#{version}/prizmal-cli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2e79d7bfb2fd2fbf3eb6c3a19a6e1c40cf20c56e6e84f2325f3aa238d6046c5f"
      url "https://github.com/PrizmalAi/prizmal-cli/releases/download/v#{version}/prizmal-cli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "prizmal"
  desc "Use Prizmal Switch with any coding-agent harness"
  homepage "https://github.com/PrizmalAi/prizmal-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "prizmal"

  # No zap stanza required
end
